config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :statements
  end

  devise_for :users, :path => 'accounts'

  devise_scope :user do
    root 'devise/sessions#new'
  end

  get '*path' => redirect('/')

end

app/models/statement.rb
class Statement < ApplicationRecord
  include CalculationsHelper
  belongs_to :user

  def regular_pay
    hourly_rate * PAY_PERIOD_HOURS
  end

  def overtime_pay
    overtime_rate * overtime_hours
  end

  def gross_pay
    regular_pay + overtime_pay
  end

  def non_taxable_wages
    health_insurance + fsa_contribution + vision_insurance + non_taxable_additional
  end

  def tax_deferred_wages
    tsp_contribution + tax_deferred_additional
  end

  def taxable_wages
    gross_pay - non_taxable_wages - tax_deferred_wages
  end

  def medicare_deduction
    (gross_pay - non_taxable_wages) * MEDICARE_PERCENTAGE / 100
  end

  def fers_deduction
    regular_pay * fers_code / 100
  end

  def state_tax
    biweekly_CA_state_tax(
      taxable_wages,
      state_exemptions,
      home_state.to_sym,
      marital_status.parameterize.underscore.to_sym,
      additional_state_allowances
    )
  end

  def oasdi_deduction
    (gross_pay - non_taxable_wages) * OASDI_PERCENTAGE / 100
  end

  def federal_tax
    biweekly_federal_tax(
      taxable_wages,
      federal_exemptions,
      marital_status.parameterize.underscore.to_sym
    )
  end

  def tsp_contribution
    if tsp_fixed_amount && tsp_fixed_amount > 0
      tsp_fixed_amount
    elsif tsp_percentage
      regular_pay * tsp_percentage / 100.0
    else
      0.0
    end
  end

  def roth_tsp_contribution
    if roth_tsp_fixed_amount && roth_tsp_fixed_amount > 0
      roth_tsp_fixed_amount
    elsif roth_tsp_percentage
      regular_pay * roth_tsp_percentage / 100.0
    else
      0.0
    end
  end

  def summed_deductions
    deductions = [
      health_insurance,
      vision_insurance,
      dental_insurance,
      life_insurance_premium,
      fsa_contribution,
      medicare_deduction,
      fers_deduction,
      oasdi_deduction,
      state_tax,
      federal_tax,
      tsp_contribution,
      roth_tsp_contribution,
      non_taxable_additional,
      taxable_additional
    ]

    deductions.sum
  end

  def take_home_pay
    gross_pay - summed_deductions
  end

  def check_for_nil_values
    all_attributes = self.attribute_names
    attributes_to_ignore = ["id", "created_at", "updated_at", "user_id"]

    attributes_to_ignore.each do |attribute|
      all_attributes.delete(attribute)
    end
    attributes_to_check = all_attributes

    attributes_to_check.each do |attribute|
      self.send(attribute + "=", 0.0) if self.send(attribute).blank?
    end
  end
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  include CalculationsHelper
  before_action :authenticate_user!

  def index
    verify_user(params)
    @statements = current_user.statements.order(created_at: :desc)
  end

  def new
    verify_user(params)

    @american_states  = american_states
    @marital_statuses = marital_statuses
    @FERS_codes       = fers_codes

    if !current_user.statements.empty?
      @statement = current_user.statements.order("created_at").last
    else
      @statement = Statement.new
    end
  end

  def create
    financial_attributes = params['statement'].permit!.to_hash
    @statement = Statement.new(financial_attributes)
    @statement.check_for_nil_values

    if params['commit'] == 'Save Calculation'
      current_user.statements << @statement
      current_user.save
    end
  end

  def show
    verify_user(params)
    @statement = get_statement(params)
  end

  def destroy
    @statement = get_statement(params)

    if @statement.destroy
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the statement."
      redirect_to action: :index
    end
  end

  private
  def get_statement(params)
    begin
    @statement = Statement.find(params['id'])
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "Statement not found"
      redirect_to :action => 'index'
    end
  end

  def verify_user(params)
    if params['user_id'].to_i != current_user.id
      flash[:notice] = "Invalid user "
      redirect_to user_statements_path(current_user.id)
    end
  end
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/statements/_calculations.html.erb
<div class="well aa-output-card">
  <h3>Current Earnings</h3>
  <span class="aa-item-title">Regular Pay</span>
  <span class="aa-item-value"><%= "$#{statement.regular_pay.round(2)}" %></span>
  <br>
  <span class="aa-item-title">Overtime Pay</span>
  <span class="aa-item-value"><%= "$#{statement.overtime_pay.round(2)}" %></span>
</div>
<div class="well aa-output-card">
  <h3>Summary</h3>
  <span class="aa-item-title aa-main-output">Take Home Pay</span>
  <span class="aa-item-value aa-main-output"><%= "$#{statement.take_home_pay.round(2)}" %></span>
  <br>
  <span class="aa-item-title">Gross Pay </span>
  <span class="aa-item-value"><%= "$#{statement.gross_pay.round(2)}" %></span>
  <br>
  <span class="aa-item-title">Taxable Wages</span>
  <span class="aa-item-value"><%= "$#{statement.taxable_wages.round(2)}" %></span>
  <br>
  <span class="aa-item-title">Non-taxable Wages</span>
  <span class="aa-item-value"><%= "$#{statement.non_taxable_wages.round(2)}" %></span>
  <br>
  <span class="aa-item-title">Tax-deferred Wages</span>
  <span class="aa-item-value"><%= "$#{statement.tax_deferred_wages.round(2)}" %></span>
  <br>
  <span class="aa-item-title">Deductions</span>
  <span class="aa-item-value"><%= "$#{statement.summed_deductions.round(2)}" %></span>
</div>
<div class="well aa-output-card">
  <h3>Deductions</h3>
  <div class="aa-output-card">
    <span class="aa-item-title">Life</span>
    <span class="aa-item-value"><%= "$#{statement.life_insurance_premium.to_f}"%></span>
    <br>
    <span class="aa-item-title">Medicare</span>
    <span class="aa-item-value"><%= "$#{statement.medicare_deduction.round(2)}" %></span>
    <br>
    <span class="aa-item-title">Retire, FERS</span>
    <span class="aa-item-value"><%= "$#{statement.fers_deduction.round(2)}" %></span>
    <br>
    <span class="aa-item-title">Tax, State</span>
    <span class="aa-item-value"><%= "$#{statement.state_tax.round(2)}" %></span>
    <br>
    <span class="aa-item-title">Vision</span>
    <span class="aa-item-value"><%= "$#{statement.vision_insurance.to_f}" %></span>
    <br>
    <span class="aa-item-title">Dental</span>
    <span class="aa-item-value"><%= "$#{statement.dental_insurance.to_f}" %></span>
    <br>
    <span class="aa-item-title">FSA-HC</span>
    <span class="aa-item-value"><%= "$#{statement.fsa_contribution.to_f}" %></span>
  </div>
  <div class="aa-output-card aa-right-column">
    <span class="aa-item-title">FEHB</span>
    <span class="aa-item-value"><%= "$#{statement.health_insurance.to_f}"%></span>
    <br>
    <span class="aa-item-title">OASDI</span>
    <span class="aa-item-value"><%= "$#{statement.oasdi_deduction.round(2)}" %></span>
    <br>
    <span class="aa-item-title">Tax, Federal</span>
    <span class="aa-item-value"><%= "$#{statement.federal_tax.round(2)}" %></span>
    <br>
    <span class="aa-item-title">TSP Savings</span>
    <span class="aa-item-value"><%= "$#{statement.tsp_contribution.round(2)}" %></span>
    <br>
    <span class="aa-item-title">Roth TSP Savings</span>
    <span class="aa-item-value"><%= " $#{statement.roth_tsp_contribution.round(2)}" %></span>
    <br>
    <span class="aa-item-title">Additional (Taxable)</span>
    <span class="aa-item-value"><%= " $#{statement.taxable_additional.to_f.round(2)}" %></span>
    <br>
    <span class="aa-item-title">Additional (Non-Taxable) </span>
    <span class="aa-item-value"><%= "$#{statement.non_taxable_additional.to_f.round(2)}" %></span>
  </div>
</div>

app/views/statements/_calculator.html.erb
<%= form_for @statement, :url => {:controller => 'statements', :action => 'create'}, method: :post, remote: true do |form| %>
  <div class="aa-form-fields">
    <h3>Rates & Hours</h3>
    <div>
      <%= form.label "Hourly Rate" %><br>
      <%= form.number_field :hourly_rate, :step => 0.01 %>
    </div>

    <div>
      <%= form.label "Overtime Rate" %><br>
      <%= form.number_field :overtime_rate, :step => 0.01 %>
    </div>

    <div>
      <%= form.label "Overtime Hours" %><br>
      <%= form.number_field :overtime_hours, :step => 0.01  %>
    </div>
  </div>
  <div class="aa-form-fields">
    <h3>Insurance</h3>
    <div>
      <%= form.label :health_insurance, 'Health (FEHB)' %><br>
      <%= form.number_field :health_insurance, :step => 0.01 %>
    </div>

    <div>
      <%= form.label :dental_insurance, 'Dental' %><br>
      <%= form.number_field :dental_insurance, :step => 0.01 %>
    </div>

    <div>
      <%= form.label "Vision" %><br>
      <%= form.number_field :vision_insurance, :step => 0.01  %>
    </div>

    <div>
      <%= form.label "Life"%><br>
      <%= form.number_field :life_insurance_premium, :step => 0.01 %>
    </div>

    <div>
      <%= form.label :fsa_contribution, 'FSA' %><br>
      <%= form.number_field :fsa_contribution, :step => 0.01  %>
    </div>
  </div>
  <div class="aa-form-fields aa-spaced">
    <h3>Exemptions & Status</h3>
    <div>
      <%= form.label :federal_exemptions, "Fed" %><br>
      <%= form.select :federal_exemptions, options_for_select((0..9).to_a, @statement['federal_exemptions']) %>
    </div>

    <div>
      <%= form.label :state_exemptions, "State" %><br>
      <%= form.select :state_exemptions, options_for_select((0..9).to_a, @statement['state_exemptions']) %><br>
    </div>

    <div>
      <%= form.label :additional_state_allowances, "Add'l" %><br>
      <%= form.select :additional_state_allowances, options_for_select((0..10).to_a, @statement['additional_state_allowances']) %><br>
    </div>

    <div>
      <%= form.label :home_state, "State" %><br>
      <%= form.select :home_state, options_for_select(@american_states, @statement['home_state']) %><br>
    </div>

    <div>
      <%= form.label :marital_status, "Marital Status" %><br>
      <%= form.select :marital_status, options_for_select(@marital_statuses, @statement['marital_status']) %><br>
    </div>
  </div>
  <div class="aa-form-fields">
    <h3>TSP & FERS</h3>

    <div>
      <%= form.label :tsp_fixed_amount, 'TSP (fixed amount)' %><br>
      <%= form.number_field :tsp_fixed_amount, :step => 0.01 %><br>
    </div>
    or,
    <div>
      <%= form.label :tsp_percentage, 'TSP (%)' %><br>
      <%= form.number_field :tsp_percentage, :step => 0.001 %><br>
    </div>

    <div>
      <%= form.label :roth_tsp_fixed_amount, 'Roth TSP (fixed amount)' %><br>
      <%= form.number_field :roth_tsp_fixed_amount, :step => 0.01 %><br>
    </div>
    or,
    <div>
      <%= form.label :roth_tsp_percentage, 'Roth TSP (%)' %><br>
      <%= form.number_field :roth_tsp_percentage, :step => 0.001 %><br>
    </div>

    <div>
      <%= form.label :fers_code, "FERS Code" %><br>
      <%= form.select :fers_code, options_for_select(@FERS_codes, @statement.fers_decimal_to_code_array(@statement['fers_code']))  %><br>
    </div>
  </div>
  <div class="aa-form-fields">
    <h3>Additional</h3>

    <div>
      <%= form.label :non_taxable_additional, 'Additional (Non-Taxable)' %><br>
      <%= form.number_field :non_taxable_additional, :step => 0.01  %><br>
    </div>

    <div>
      <%= form.label :taxable_additional, 'Additional (Taxable)' %><br>
      <%= form.number_field :taxable_additional, :step => 0.01  %><br>
    </div>
  </div><br>
  <div>
    <%= form.submit "Calculate", class: 'btn btn-primary' %>
    <%= form.submit "Save Calculation", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/statements/create.html.erb
<!--
  This view is only needed to prevent tests from failing. The #create action
  test of the "statements_controller" will fail without this view. With and
  without this view, the application seems to run without any issues.

  Error when running "rspec spec/controllers/statements_controller_spec.rb "

  "
    1) StatementsController POST #create returns http success
       Failure/Error: post :create, params: {user_id: user, statement: statement_attributes }

       ActionController::UnknownFormat:
         StatementsController#create is missing a template for this request format and variant.

         request.formats: ["text/html"]
         request.variant: []
   "
   My hypothesis is that you need to let the test know to not look for a view
   but instead send look for the file "create.js.erb" instead. This is because
   "create" gets triggered from the from in the "new" view using AJAX. So,
   further research is needed to make the test more accurate and delete this
   otherwise useless view.
 -->

app/views/statements/create.js.erb
$("#calculations").html("<%= escape_javascript(render partial: 'calculations', locals: { statement: @statement }) %>");

app/views/statements/index.html.erb
<br>
<div>
  <%= button_to 'New Calculation', new_user_statement_path, method: :get, class: 'btn btn-success' %>
</div><br>

<h3>Your Statements</h3>

<div>
  <% @statements.each do |statement| %>
    <div class="well" style="overflow:auto">
      <div>
        <span style="font-weight:bold">Date Created:</span> <%= statement.created_at.in_time_zone("Pacific Time (US & Canada)").strftime("%a %B %d, %Y %l:%M %p") %> <br>
        <span style="font-weight:bold">Take-Home Pay:</span> <%= "$#{statement.take_home_pay.round(2)}" %><br>
        <span style="font-weight:bold">Regular Pay:</span> <%= "$#{statement.regular_pay.round(2)}" %><br>
        <span style="font-weight:bold">OT Hours:</span> <%= statement.overtime_hours.round(2) %>
      </div>
      <br>
      <div style="float:right">
        <%= button_to 'Details', {controller: 'statements', action: 'show', id: statement.id}, method: 'get', class: 'btn btn-primary btn-xs', form: {style: 'display:inline-block;'} %>
        <%= button_to 'Delete Statement',{controller: 'statements', action: 'destroy', id: statement.id}, method: 'delete', class: 'btn btn-danger btn-xs', form: {style: 'display:inline-block;'} %>
      </div>
    </div>
  <% end %>
</div>

app/views/statements/new.html.erb
<%= render partial: "calculator" %>
<br>
<div id="calculations"></div>

app/views/statements/show.html.erb
<div>
  <h1>Statement</h1>
  <h3><%= @statement.created_at.in_time_zone("Pacific Time (US & Canada)").strftime("%a %B %d, %Y @%H:%M %p") %></h3>
</div>

<div class="well aa-output-card">
  <span class="aa-item-title">Hourly rate:</span>
  <span class="aa-item-value">$<%= @statement.hourly_rate %></span>
  <br>
  <span class="aa-item-title">OT Rate:</span>
  <span class="aa-item-value">$<%= @statement.overtime_rate %></span>
  <br>
  <span class="aa-item-title">Marital Status:</span>
  <span class="aa-item-value"><%= @statement.marital_status %></span>
  <br>
  <span class="aa-item-title">Fed Exemptions:</span>
  <span class="aa-item-value"><%= @statement.federal_exemptions %></span>
  <br>
  <span class="aa-item-title">State Exemptions:</span>
  <span class="aa-item-value"><%= @statement.state_exemptions %></span>
</div>

<div class="well aa-output-card">
  <span class="aa-item-title">Gross Pay:</span>
  <span class="aa-item-value"><%= "$#{@statement.gross_pay.round(2)}" %></span>
  <br>
  <span class="aa-item-title">Taxable Wages:</span>
  <span class="aa-item-value"><%= "$#{@statement.taxable_wages.round(2)}" %></span>
  <br>
  <span class="aa-item-title">Nontaxable Wages:</span>
  <span class="aa-item-value"><%= "$#{@statement.non_taxable_wages.round(2)}" %></span>
  <br>
  <span class="aa-item-title">Tax Deferred Wages:</span>
  <span class="aa-item-value"><%= "$#{@statement.tax_deferred_wages.round(2)}" %></span>
  <br>
  <span class="aa-item-title">Deductions:</span>
  <span class="aa-item-value"><%= "$#{@statement.summed_deductions.round(2)}" %></span>
  <br>
  <span class="aa-item-title aa-main-output">Net Pay:</span>
  <span class="aa-item-value aa-main-output"><%= "$#{@statement.take_home_pay.round(2)}"%></span>
</div>

<div class="well aa-card-margin">
  <h3>Current Earning</h3>
  <span class="aa-item-title aa-no-right-margin">Regular Pay: </span>
  <span class="aa-right-margin"><%= "$#{@statement.regular_pay.round(2)}" %></span>

  <span class="aa-item-title aa-no-right-margin">Overtime Hours:</span>
  <span class="aa-right-margin"><%= @statement.overtime_hours %></span>

  <span class="aa-item-title aa-no-right-margin">Overtime Pay:</span>
  <span><%= "$#{@statement.overtime_pay.round(2)}" %></span>
</div>

<div class="well aa-output-card">
  <h3>Deductions</h3>
  <div class="aa-output-card">
    <span class="aa-item-title">Life:</span>
    <span class="aa-item-value"><%= "$#{@statement.life_insurance_premium}" %></span>
    <br>
    <span class="aa-item-title">Medicare:</span>
    <span class="aa-item-value"><%= "$#{@statement.medicare_deduction.round(2)}" %></span>
    <br>
    <span class="aa-item-title">Retire, FERS</span>
    <span class="aa-item-value"><%= "$#{@statement.fers_deduction.round(2)}" %></span>
    <br>
    <span class="aa-item-title">Tax, state</span>
    <span class="aa-item-value">$<%= @statement.state_tax.round(2) %></span>
    <br>
    <span class="aa-item-title">Vision</span>
    <span class="aa-item-value">$<%= @statement.vision_insurance.to_f %></span>
    <br>
    <span class="aa-item-title">Dental</span>
    <span class="aa-item-value">$<%= @statement.dental_insurance.to_f %></span>
    <br>
    <span class="aa-item-title">FSA-HC</span>
    <span class="aa-item-value">$<%= @statement.fsa_contribution.to_f %></span>
  </div>
  <div class="aa-output-card">
    <span class="aa-item-title">FEHB:</span>
    <span class="aa-item-value">$<%= @statement.health_insurance %></span>
    <br>
    <span class="aa-item-title">OASDI:</span>
    <span class="aa-item-value">$<%= @statement.oasdi_deduction.round(2) %></span>
    <br>
    <span class="aa-item-title">Tax, federal</span>
    <span class="aa-item-value">$<%= @statement.federal_tax.round(2) %></span>
    <br>
    <span class="aa-item-title">TSP savings</span>
    <span class="aa-item-value">$<%= @statement.tsp_contribution.round(2) %></span>
    <br>
    <span class="aa-item-title">Roth TSP Savings</span>
    <span class="aa-item-value">$<%= @statement.roth_tsp_contribution.round(2)%></span>
    <br>
    <span class="aa-item-title">Additional (Taxable)</span>
    <span class="aa-item-value">$<%= @statement.taxable_additional.to_f.round(2) %></span>
    <br>
    <span class="aa-item-title">Additional (Non-Taxable) </span>
    <span class="aa-item-value">$<%= @statement.non_taxable_additional.to_f.round(2) %></span>
  </div>
</div>

<div>
  <%= button_to 'Delete Statement',{controller: 'statements', action: 'destroy', id: @statement.id}, method: 'delete', class: "btn btn-danger" %>
</div>